name: ci

on:
  push: 
    branches: ["main"]
  pull_request: 
    branches: ["main", "release/**"]
jobs:
  test:
    strategy:
      matrix:
        consul-version: [1.11.x, 1.11.x+ent]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Install Consul
      uses: nickethier/action-setup-hashicorp-tool@main #TODO: update action when migrated to hc org
      with:
        product: consul
        version: ${{ matrix.consul-version }}

    - id: go-cache-paths
      name: Setup Go Cache paths 
      run: |
        echo "::set-output name=go-build-cache::$(go env GOCACHE)"
        echo "::set-output name=go-mod-cache::$(go env GOMODCACHE)"

    - name: Go Build Cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.go-cache-paths.outputs.go-build-cache }}
        key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}

    - name: Go Mod Cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.go-cache-paths.outputs.go-mod-cache }}
        key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}

    - name: Test
      run: |
        go test -race ./...
